[package]
name = "rust_stud1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ia_devices = { path = "lib/ia_devices" }  # this is our lib, now in an external crate